### ISSUE TITLE
安卓蓝牙扫描问题

### ISSUE THREAD

**Issue by Deepblue1996** [pencilso/ManyBlue#1]
安卓蓝牙扫描设备问题，安卓6.0以上系统测试都正常，可以扫描到自己的蓝牙主板，就安卓6.0扫不到我自己那个蓝牙主板，但是可以扫描到其他蓝牙设备，是不是安卓6.0有什么特殊要求？

**Comment by songlongkuan** [comment]
5.0-8.0的系统我以前都测试过的，正常的，部分品牌的6.0+，比如说华为，需要动态申请定位权限的，不知你有没有申请？

**Comment by Deepblue1996** [comment]
已经解决，主板信号错容率问题
